### ISSUE TITLE
update package with mongo driver 3

### ISSUE THREAD

**Issue by RezaErfani67** [hex7c0/mongodb-backup#34] opened 2019-04-27 10:10 UTC
mongo driver 2 is old and there is some problems on query  with _id...
please update packege with mongo driver 3...
it need some changes such as snapshot stream or mongo client connection.

**Comment by Phoscur** [comment] 2019-07-27 12:39
Duplicate of #27, see PR https://github.com/hex7c0/mongodb-backup/pull/36

**Comment by RezaErfani67** [comment] 2019-09-02 05:54
thanks alot...
should install [this](https://www.npmjs.com/package/mongodb-backup-4x)

**Closed as completed** 2019-09-02 05:54 UTC
